benefit_categories:
  clinical_quality:
    confidence_factors:
      case_studies: 0.8
      peer_reviewed_studies: 0.9
      pilot_results: 0.7
      vendor_claims: 0.5
    measurement_frequency: monthly
    weight: 0.4
  financial_impact:
    confidence_factors:
      actual_savings: 0.95
      estimated_benefits: 0.6
      market_benchmarks: 0.75
      validated_projections: 0.85
    measurement_frequency: quarterly
    weight: 0.3
  operational_efficiency:
    confidence_factors:
      documented_processes: 0.9
      historical_data: 0.8
      industry_benchmarks: 0.7
      vendor_estimates: 0.6
    measurement_frequency: monthly
    weight: 0.3
confidence_threshold: 0.8
discount_rate: 0.08
risk_multipliers:
  adoption_risk: 0.85
  clinical_risk: 0.8
  competitive_risk: 0.9
  implementation_risk: 0.9
  regulatory_risk: 0.95
time_horizon_months: 36
